[theme]
base = 'light'
primaryColor = '#000000'

[server]
enableCORS=false
fileWatcherType = "none"
maxUploadSize = 1024
maxMessageSize = 1024

[browser]
serverAddress = "localhost"
gatherUsageStats = false