# .streamlit/secrets.toml
[protection]
psw_gateway = "false"

[cookie]
cookie_name   = "YoutubeToText"
cookie_hash_psw   = "Az3rTy-1465"
cookie_expiry_duration = 30

[page]
page_title      = "Speech to text converter"
page_icon       = ":ninja:" #https://www.webfx.com/tools/emoji-cheat-sheet/
layout          = "centered"
footer          = """<style> a:link , a:visited{ color: blue; background-color: transparent; text-decoration: underline; } a:hover, a:active { color: red; background-color: transparent; text-decoration: underline; } .footer { position: fixed; left: 0; bottom: 0; width: 100%; background-color: white; color: black; text-align: center; } </style> <div class="footer"> <p>Developed by <a style="color: black;" href="https://azerty-labs.com" target="_blank"><bold>Azerty-labs</bold></a></p> </div>"""
hide_menu_style = "<style>#MainMenu {visibility: hidden;}</style>"

[data]
database_path = "./database"